
## Imports


In [1]:
# %pip install numpy
# %pip install matplotlib
import numpy as np
import matplotlib.pyplot as plt

## Dataset

In [2]:
XY_or_port = np.array([
            [0,0, 0],
            [0,1, 1],
            [1,0, 1],
            [1,1, 1],
           ])

XY_xor_port =  np.array([
            [0,0, 0],
            [0,1, 1],
            [1,0, 1],
            [1,1, 0],
           ])

XY_AND_port =  np.array([
            [0,0, 0],
            [0,1, 0],
            [1,0, 0],
            [1,1, 1],
           ])

XY_Execise9_port =  np.array([
            [0,0, 0],
            [0,1, 1],
            [1,0, 0],
            [1,1, 0],
           ])

XY_Execise11_port =  np.array([
            [0,0, 1],
            [0,1, 1],
            [1,0, 0],
            [1,1, 1],
           ])

dataset = {
    'OR':  XY_or_port,
    'XOR': XY_xor_port,
    'AND': XY_AND_port,
    'Exercise9': XY_Execise9_port,
    'Exercise11': XY_Execise11_port,
}

dataset

{'OR': array([[0, 0, 0],
        [0, 1, 1],
        [1, 0, 1],
        [1, 1, 1]]),
 'XOR': array([[0, 0, 0],
        [0, 1, 1],
        [1, 0, 1],
        [1, 1, 0]]),
 'AND': array([[0, 0, 0],
        [0, 1, 0],
        [1, 0, 0],
        [1, 1, 1]]),
 'Exercise9': array([[0, 0, 0],
        [0, 1, 1],
        [1, 0, 0],
        [1, 1, 0]]),
 'Exercise11': array([[0, 0, 1],
        [0, 1, 1],
        [1, 0, 0],
        [1, 1, 1]])}

## Model

In [3]:
def heaviside_step_function(a):
    if int(a) >= 0:
        return 1
    return 0

class SinglePerceptronForLogicPorts():
    def __init__(self, activation_function = heaviside_step_function) -> None:
        self.W = []
        self.activation_function = activation_function

    def predict(self, X):
        dot_product = X @ self.W.T
        y_hat = self.activation_function(dot_product)
        return y_hat

    def fit(self, data, W=[], bias = 1.0, learning_rate = 1.0):
        X, Y = self.__get_X_Y(data, bias)
        N = len(Y) # N X D
        self.W = W

        if len(W) == 0:
            self.W = np.zeros(N)
            
        stop = False

        while(stop == False):
            for i in range(N):
                y_hat = self.predict(X[i])
                y = Y[i]
                if y < y_hat:

                    self.__print_weight(W, 'old')

                    self.W = learning_rate * self.__subtract_update_W(X[i], self.W)

                    self.__print_weight(W, 'new')

                elif y > y_hat:

                    self.__print_weight(W, 'old')

                    self.W = learning_rate * self.__sum_update_W(X[i], self.W)

                    self.__print_weight(W, 'new')

            stop = self.__stop_train(X, Y)

        print('The training ended | Final Weights=')
        print(W)

    def __print_weight(self, W, status):
        print(status + '_weight =')
        print(W)

    def __get_X_Y(self, data_matrix, bias):
        X = []
        Y = []
        for line in data_matrix:
            X.append(np.append(bias, line[:2]))
            Y.append(line[2])
        return np.array(X), np.array(Y)

    def __stop_train(self, X, Y):
        interaction = len(Y)
        for i in range(interaction):
            y_hat = self.predict(X[i])
            y = Y[i]
            if y != y_hat:
                return False
        return True

    def __sum_update_W (self, X, W):
        return W + X

    def __subtract_update_W (self, X, W):
        return  W - X



## Run Model

In [8]:
initial_W = np.array([0,0,1])
data = dataset['OR']

model = SinglePerceptronForLogicPorts()
model.fit(data,initial_W,)

old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =
[0 0 1]
old_weight =
[0 0 1]
new_weight =


KeyboardInterrupt: 