
## Imports


In [1]:
%pip install numpy
import numpy as np

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 14.0 MB 1.9 MB/s eta 0:00:01     |████████████████████████▎       | 10.6 MB 1.9 MB/s eta 0:00:02
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


## Dataset

In [5]:
XY_or_port = np.array([
            [0,0, 0],
            [0,1, 1],
            [1,0, 1],
            [1,1, 1],
           ])

XY_xor_port =  np.array([
            [0,0, 0],
            [0,1, 1],
            [1,0, 1],
            [1,1, 0],
           ])

XY_AND_port =  np.array([
            [0,0, 0],
            [0,1, 0],
            [1,0, 0],
            [1,1, 1],
           ])

XY_Execise9_port =  np.array([
            [0,0, 0],
            [0,1, 1],
            [1,0, 0],
            [1,1, 0],
           ])

dataset = {
    'OR':  XY_or_port,
    'XOR': XY_xor_port,
    'AND': XY_AND_port,
    'Exercise9': XY_Execise9_port,
}

dataset

{'OR': array([[0, 0, 0],
        [0, 1, 1],
        [1, 0, 1],
        [1, 1, 1]]),
 'XOR': array([[0, 0, 0],
        [0, 1, 1],
        [1, 0, 1],
        [1, 1, 0]]),
 'AND': array([[0, 0, 0],
        [0, 1, 0],
        [1, 0, 0],
        [1, 1, 1]]),
 'Exercise9': array([[0, 0, 0],
        [0, 1, 1],
        [1, 0, 0],
        [1, 1, 0]])}

## Model

In [3]:
class SinglePerceptronForLogicPorts():
    def __init__(self, activation_function) -> None:
        self.W = None
        self.activation_function = activation_function

    def predict(self, X, W):
        dot_product = X @ W.T
        y_hat = self.activation_function(dot_product)
        return y_hat

    def fit(self, W, data, bias = 1.0, learning_rate = 1.0):
        X, Y = self.__get_X_Y(data, bias)
        N = len(Y) # N X D
        stop = False

        while(stop == False):
            for i in range(N):
                y_hat = self.predict(X[i], W)
                y = Y[i]
                if y < y_hat:

                    self.__print_weight(W, 'old')

                    W = learning_rate * self.__subtract_update_W(X[i], W)

                    self.__print_weight(W, 'new')

                elif y > y_hat:

                    self.__print_weight(W, 'old')

                    W = learning_rate * self.__sum_update_W(X[i], W)

                    self.__print_weight(W, 'new')

            stop = self.__stop_train(X, W, Y)

        print('The training ended | Final Weights=')
        print(W)

    def __print_weight(self, W, status):
        print(status + '_weight =')
        print(W)

    def __get_X_Y(self, data_matrix, bias):
        X = []
        Y = []
        for line in data_matrix:
            X.append(np.append(bias, line[:2]))
            Y.append(line[2])
        return np.array(X), np.array(Y)

    def __stop_train(self, X, W, Y):
        interaction = len(Y)
        for i in range(interaction):
            y_hat = self.predict(X[i], W)
            y = Y[i]
            if y != y_hat:
                return False
        return True

    def __sum_update_W (self, X, W):
        return W + X

    def __subtract_update_W (self, X, W):
        return  W - X



## Run Model

In [6]:
initial_W = np.array([0,0,0])
data = dataset['Exercise9']

model = SinglePerceptronForLogicPorts()
model.fit(initial_W,data)

old_weight =
[0 0 0]
new_weight =
[-1.  0.  0.]
old_weight =
[-1.  0.  0.]
new_weight =
[0. 0. 1.]
old_weight =
[0. 0. 1.]
new_weight =
[-1. -1.  1.]
The training ended | Final Weights=
[-1. -1.  1.]
